# *** Welcome to the example Parsy application's configuration file! ***
#
# This launcher is built on Jaunch (https://github.com/scijava/jaunch).
#
# There is a general layer of launcher configuration in the jaunch.toml file.
# The contents below define Parsy's particular launcher behavior and features,
# on top of Jaunch's "sensible default" functionality.
#
# See that jaunch.toml file for more details about Jaunch configuration.

jaunch-version = 1

program-name = 'Parsy'

java-version-min = '8'
#java-version-max = '21'

classpath = [
    '${app-dir}/lib/*.jar',
]

max-heap = '128m' # '50%'

jvm-args = [
]

main-class-candidates = [
    'org.scijava.parsington.Main',
]

main-args = [
]
