# *** Welcome to the example Hello application's configuration file! ***
#
# The Hello application uses Java's Swing widget toolkit
# to display a graphical dialog with a greeting message.
#
# This launcher is built on Jaunch (https://github.com/scijava/jaunch).
#
# The contents below define Hello's particular launcher behavior and features,
# on top of Jaunch's "sensible default" functionality.
#
# See the common.toml file for more details about Jaunch configuration.

jaunch-version = 2

program-name = 'Hello'

includes = ['jvm.toml']

modes = ['LAUNCH:JVM']

jvm.version-min = '8'

jvm.classpath = ['${app-dir}']

jvm.main-class = ['HelloSwing']
