# *** Welcome to the Icy launcher's configuration file! ***
#
# Read about Icy at <https://icy.bioimageanalysis.org>.
#
# This Icy launcher is built on Jaunch (https://github.com/scijava/jaunch).
#
# The contents below define Icy's particular launcher behavior and features,
# on top of Jaunch's "sensible default" functionality.
#
# See the common.toml file for more details about Jaunch configuration.

jaunch-version = 1

program-name = 'Icy'

includes = ['jvm.toml']

modes = ['LAUNCH:JVM']

jvm.version-min = '8'

jvm.classpath = [
    'updater.jar',
]

jvm.max-heap = '25%'

jvm.runtime-args = [
    'OS:LINUX|ARCH:X64|-Djava.library.path=${app-dir}/lib/unix64',
    'OS:LINUX|ARCH:X86|-Djava.library.path=${app-dir}/lib/unix32',
    'OS:MACOSX|ARCH:ARM64|-Djava.library.path=${app-dir}/lib/maca64',
    'OS:MACOSX|ARCH:X64|-Djava.library.path=${app-dir}/lib/mac64',
    'OS:WINDOWS|ARCH:X64|-Djava.library.path=${app-dir}\lib\win64',
    'OS:WINDOWS|ARCH:X86|-Djava.library.path=${app-dir}\lib\win32',
]

jvm.main-class = [
    'icy.updater.Main',
]
