# *** Welcome to the example Jy application's configuration file! ***
#
# The Jy application launches the Jython interpreter.
# Read about Jython at <https://www.jython.org/>.
#
# This launcher is built on Jaunch (https://github.com/scijava/jaunch).
#
# The contents below define Jy's particular launcher behavior and features,
# on top of Jaunch's "sensible default" functionality.
#
# See the common.toml file for more details about Jaunch configuration.

jaunch-version = 1

program-name = 'Jy'

includes = ['jvm.toml']

modes = ['LAUNCH:JVM']

jvm.version-min = '8'

jvm.classpath = [
    '${app-dir}/lib/*.jar',
]

jvm.max-heap = '75%'

jvm.runtime-args = [
    '-Dpython.import.site=false',
    '-Dpython.cachedir.skip=true',
    '-Dpython.console.encoding=UTF-8',
]

jvm.main-class = ['org.python.util.jython']
