# *** Welcome to the example Parsy application's configuration file! ***
#
# This launcher is built on Jaunch (https://github.com/scijava/jaunch).
#
# The contents below define Parsy's particular launcher behavior and features,
# on top of Jaunch's "sensible default" functionality.
#
# See the common.toml file for more details about Jaunch configuration.

jaunch-version = 1

program-name = 'Parsy'

includes = ['jvm.toml']

jvm.version-min = '8'

jvm.classpath = [
    '${app-dir}/lib/*.jar',
]

jvm.max-heap = '64m'

jvm.main-class = ['org.scijava.parsington.Main']
