# *** Welcome to the Paunch configuration file! ***
#
# Paunch is a Python launcher built on Jaunch (https://github.com/scijava/jaunch).
#
# One advantage of Paunch over the normal python launcher is that on macOS,
# Paunch starts Python on a separate pthread, and starts the AppKit event loop
# on the main thread, so that GUIs (especially Java-based AWT/Swing GUIs) can
# successfully operate without hanging.
#
# The contents below define Paunch's particular launcher behavior and features,
# on top of Paunch's "sensible default" functionality.
#
# See the common.toml file for more details about Jaunch configuration.

jaunch-version = 1

program-name = 'Paunch'

includes = ['python.toml']

python.version-min = '3.8'
