name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        # Note: This list pins to the newest available public runner image
        # for each supported platform. Some of these targets need to roll
        # forward as GitHub advances new runners. See the current list at:
        # https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
        os:
        - ubuntu-latest     # Linux x64
        - macos-13          # macOS x64
        - windows-latest    # Windows x64
        - ubuntu-22.04-arm  # Linux arm64
        - macos-latest      # macOS arm64
        - windows-11-arm    # Windows arm64

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'
        cache: 'gradle'

    - name: Cache Kotlin Native
      id: cache-konan
      uses: actions/cache@v4
      with:
        path: ~/.konan
        key: ${{ runner.os }}-build-konan-${{ hashFiles('*gradle.*') }}
        restore-keys: |
          ${{ runner.os }}-build-konan-

    - name: Install aarch64-linux-gnu-gcc
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu

    - name: Build binaries and assemble distribution
      run: make dist

    - name: Upload platform distribution
      uses: actions/upload-artifact@v4
      with:
        name: jaunch-${{ matrix.os }}
        path: jaunch.tar.gz

  dist:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache the .cache folder
      id: cache-cache
      uses: actions/cache@v4
      with:
        path: .cache
        key: ${{ runner.os }}-dist-cache

    - name: Download platform distributions
      uses: actions/download-artifact@v4

    - name: Merge platform distributions
      run: |
        for tar in jaunch-*/jaunch.tar*; do tar xf "$tar"; done

    - name: Assemble distribution
      run: |
        bash -c "tar czf jaunch.tar.gz dist"

    - name: Upload merged distribution
      uses: actions/upload-artifact@v4
      with:
        name: jaunch
        path: jaunch.tar.gz

  test:
    needs: [dist]
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        # Note: This list pins to the oldest available public runner image
        # for each supported platform. These targets need to roll forward as
        # GitHub deprecates and removes old runners. See the current list at:
        # https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
        os:
        - ubuntu-22.04      # Linux x64
        - macos-13          # macOS x64
        - windows-2022      # Windows x64
        - ubuntu-22.04-arm  # Linux arm64
        - macos-14          # macOS arm64
        - windows-11-arm    # Windows arm64

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'
        cache: 'gradle'
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Cache the .cache folder
      id: cache-cache
      uses: actions/cache@v4
      with:
        path: .cache
        key: ${{ runner.os }}-dist-cache

    - name: Build demo apps
      run: make demo

    - name: Install prysk
      run: pip install prysk

    - name: Run the tests
      run: |
        cd test
        prysk *.t

