name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'
        cache: 'gradle'

    - name: Cache Kotlin Native
      id: cache-konan
      uses: actions/cache@v4
      with:
        path: ~/.konan
        key: ${{ runner.os }}-build-konan-${{ hashFiles('*gradle.*') }}
        restore-keys: |
          ${{ runner.os }}-build-konan-

    - name: Build
      run: make compile-all

    - uses: actions/upload-artifact@v4
      with:
        name: launcher-${{ matrix.os }}
        path: |
          build/launcher*
          build/bin
